document.addEventListener('DOMContentLoaded', () => {
  //   const tituloID = document.getElementById('h1First')
  //   const tituloClass = document.getElementsByClassName('h1First2')
  const tituloQueri = document.querySelector('.h1First2')
  const tituloQueriAll = document.querySelectorAll('.h1First2')
  const tituloQueriElemt = document.querySelector('[atributoElemento = "LAL"]')
  const tituloQueriID = document.querySelector('#h1First2')
  //   const tituloQueriElemtAll = document.querySelectorAll('[atributoElemento]')
  const ptitulo = document.querySelector('p:nth-child(5)')
  const ptitulo2 = document.querySelector('#h1First2 + p + p +p')
  const ptitulo3 = document.querySelectorAll('p')

  //   console.log('titulo', tituloID)
  //   console.log('titulo', tituloClass)
  console.log('tagName', tituloQueri)
  console.log('tagName', tituloQueriAll)
  console.log('tagName', tituloQueriElemt)
  console.log('tagName', tituloQueriID)
  console.log('tagName', ptitulo)
  console.log('tagName', ptitulo2)
  console.log('tagName', ptitulo3)
  //   console.log('tagName', tituloQueriElemtAll)
})
